### ISSUE TITLE
Review conceptual model from workshop #2

### ISSUE THREAD

**Issue by ashepherd** [UFOKN/Knowledge-Graph#5]
@ashepherd has pictures of the drawings and will post here. We can use these and our existing conceptual model to build the first ontology so that we can start publishing data against it. THis needs to be done quickly, so we can:

- [ ] Publish the ontology.
- [ ] Get data published
- [ ] Test Competency Queries
- [ ] Iterate on ontology & data graph publishing
- [ ] Possibly test Mike's prototypes working off the graph.

**Comment by ashepherd** [comment]
![IMG_3074](https://user-images.githubusercontent.com/2117576/73672644-83352f80-466a-11ea-9682-113f5f76ca32.jpg)
![IMG_3076](https://user-images.githubusercontent.com/2117576/73672645-83352f80-466a-11ea-831e-040c18bd4b60.jpg)
![IMG_3075](https://user-images.githubusercontent.com/2117576/73672646-83352f80-466a-11ea-966e-1d7534c506c6.jpg)

**Comment by ashepherd** [comment]
![UFOKN-Data](https://user-images.githubusercontent.com/2117576/73681919-85a08500-467c-11ea-8535-770bce22e52a.png)

drawings compiled together

**Comment by ashepherd** [comment]
@thahmann I can build the initial ontology based on this drawing from workshop #2 and if you and Shirley don't mind iterating on it, @fils and I can follow your lead on how the data graph should be built. 

The point of getting this first ontology up and published will be to help us publish the data graph and evaluate the competency questions. Let me know if you disagree or if we should take a different course of action.

**Comment by ashepherd** [comment]
Added ontology to WebProtege (See Adam or Torsten for URL)
Reviewed with team on tech call 2/6

**Comment by thahmann** [comment]
Updated the conceptual model and created ontologies for all parts except the information about specific models.
